### ISSUE TITLE
Keeps prompting for update

### ISSUE THREAD

**Issue by glueckpress** [woocommerce/woocommerce-beta-tester#1]
After the first beta and database update, the plugin keeps prompting for an update from 2.4.0-dev to 2.4.0-beta2, no matter how often I run that update.

![bildschirmfoto 2015-07-15 um 19 13 48](https://cloud.githubusercontent.com/assets/308422/8704785/a41a53ca-2b25-11e5-8f86-e7efe183dd13.png)

**Comment by mikejolley** [comment]
Our bad; when @claudiosmweb tags beta 3 the version will be set correctly.

**Comment by glueckpress** [comment]
Okies.

**Comment by claudiosanches** [comment]
Tag ready!

**Comment by glueckpress** [comment]
Works as expected now. Nice, thanks! Makes beta testing a whole lot easier.
