### ISSUE TITLE
The radio button for selected version after switching isn't selected

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-beta-tester#104]
On some sites (such as a JN site), when switching versions, the selected version isn't always selected:

<img width="1290" alt="Screen Shot 2021-10-28 at 11 19 16" src="https://user-images.githubusercontent.com/71906536/139304275-1deed5ef-009c-422c-bcfa-443b8d667724.png">

**Comment by apeksha10** [comment]
I am able to replicate the above issue

steps : 
1. Try to switch the WooCommerce version from 5.6.0 to 5.9.0 
2. After selecting WC version 5.9.0, click on the switch button 
3. Successful message appears but switching version isn't selected.

![](https://content.screencast.com/users/ApekshaShah/folders/Capture/media/fadab16b-b6ca-4971-951a-723f62dc1bc0/LWR_Recording.png)

4. Plugin page 

![](https://content.screencast.com/users/ApekshaShah/folders/Capture/media/cd78dec1-772f-4fd7-a8c4-6d1db25db7d3/LWR_Recording.png)

**Comment by zhongruige** [comment]
Found the root cause of this issue: the version is coming in as upper-case and doing a compare on the lower-case (e.g. checking if `5.9.0-rc.2` equals `5.9.0-RC.2`. As a result, both the radio button wasn't selected and the `Installed Version` text wasn't showing.

**Comment by apeksha10** [comment]
I have uploaded the latest copy of the WooCommerce Beta copy plugin that is v 2.0.5

Still, I am able to replicate the above issue

![LWR_Recording](https://user-images.githubusercontent.com/20852893/147191623-28c7fd7d-ed69-4364-ae67-f70571b841cc.png)

![LWR_Recording](https://user-images.githubusercontent.com/20852893/147191697-f5bb7bd9-614c-4b48-8f37-b24f8fe6b3f2.png)

**Comment by rrennick** [comment]
> I have uploaded the latest copy of the WooCommerce Beta copy plugin that is v 2.0.5

@apeksha10 The issue you are having is different issue than the one reported:

> On some sites, when switching versions, the selected version isn't always selected

It looks like the issue you have is that the selected version is not being installed. 

When you install a plugin through Plugins -> Add New, do you have to provide SFTP credentials? If so, the beta tester isn't able to install the selected version due to permissions. If you are able to install a plugin with the plugin installer without credentials, please create a new issue.

**Comment by apeksha10** [comment]
Thanks 

I have raised another issue. woocommerce/woocommerce#32117
