### ISSUE TITLE
[Feedback Bar] Switch version

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-beta-tester#14]
A plugin row action which takes the user to the version selection screen outlined in https://github.com/woocommerce/woocommerce-beta-tester/issues/9

**Comment by bor0** [comment]
@mikejolley are these row actions same as the feedback bar ones (e.g. #22, #23), or is it a separate thing?

**Comment by mikejolley** [comment]
Yes same thing/link.

**Comment by bor0** [comment]
The fix for this would be similar to #27, once #9 is resolved.

**Comment by bor0** [comment]
Fixed by @peterfabian in a35b854.
