### ISSUE TITLE
[Feedback Bar] Show version information

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce-beta-tester#21]
We could display a modal or something to show release information from GitHub API which corresponds to current version.

GitHub lets you add text for each release.

We could add some information there regarding features and things to test.

E.g. API: https://api.github.com/repos/woocommerce/woocommerce/releases

**Comment by bor0** [comment]
@mikejolley should this be a separate screen, or enough to just display it somewhere within
<img width="394" alt="screen shot 2018-06-05 at 10 59 37 am" src="https://user-images.githubusercontent.com/1620929/40966003-938bf548-68af-11e8-914b-7692cac3c568.png">

**Comment by bor0** [comment]
also cc @kloon for question above

**Comment by kloon** [comment]
Not sure what this option should do? What version info should it display? Like all the available versions?

**Comment by bor0** [comment]
I was thinking maybe something along the lines of `Current channel: test`, and we should also have `Current version: 3.4.2-rc.2` or something.

**Comment by kloon** [comment]
If it is just to display the current version then I think we should just add it as part of the admin bar, no need for a new screen.
