### ISSUE TITLE
Offer to install WooCommerce if it's not already

### ISSUE THREAD

**Issue by johnbillion** [woocommerce/woocommerce-beta-tester#56]
Installing and activating WooCommerce Beta Tester presents a helpful button to `Activate WooCommerce` if it isn't already, but if WooCommerce isn't actually installed then clicking this button presents an unhelpful `wp_die()` message stating `Plugin file does not exist`.

It would be neat if clicking this downloaded and installed the beta version of WooCommerce if it's not already installed.

**Comment by claudiosanches** [comment]
See #57
