### ISSUE TITLE
Folder namespace breaking installs

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/woocommerce-beta-tester#6]
I had someone else comment on this bug so I tested it out myself as well to double check.  What I find somewhat **_strange_** is that I don't remember this happening before ....like... ever! 🤔 

Somewhere in the download process, it's changing the folder name from `woocommerce` to `woocommerce-plus-bonus-text` which, of course, yields the WSOD.  No big deal for anyone using this plugin, but I thought, "Ya know, one day I should make myself a note and look into why that's happening and see if I can fix it."

Consider this my _"note-to-self"_

**Comment by ghost** [comment]
The point of the Beta Tester Plugin is to avoid hassle in particular when WC folder name changes. This is what this article claims: https://woocommerce.wordpress.com/2015/07/25/how-to-beta-test-woocommerce/.

I find that every time I update through the beta tester plugin, the folder gets renamed to something like `woocommerce-woocommerce-594aa66`. This obviously breaks the WP Loop and all my plugins report that Woocommerce needs to be installed even if the release candidate is active.
So in essence the very problem that the Beta Tester Plugin is trying to tackle is not being tackled. So I'm reverting back to uploading WC manually.

Please consider this as a priority.

**Comment by seb86** [comment]
It is due to [this filter.](https://github.com/woocommerce/woocommerce-beta-tester/blob/master/woocommerce-beta-tester.php#L70)

**Comment by seb86** [comment]
It should just return "woocommerce" as the folder name no matter what the name of the zip file GitHub returns.

**Comment by mikejolley** [comment]
On it.
