### ISSUE TITLE
Styles: switch version popup title is too long

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/woocommerce-beta-tester#61]
When opening this popup:

![image](https://user-images.githubusercontent.com/282234/75160568-8926a980-571a-11ea-9e09-4b48bddb5ff8.png)

I see that its title:
> Are you sure you want to switch the version of WooCommerce plugin?

is rather long and covers the `X` button.

---

Dell XPS 13" with QHD+ built-in display, Chrome 80, Windows 10, WooCommerce Beta Tester 2.0.1, active plugins: Dummy Gateway for, WooCommerce, WooCommerce, WooCommerce Admin, WooCommerce Beta Tester

**Comment by rrennick** [comment]
@slaFFik Do you still see this issue with WP 5.5?

**Comment by slaFFik** [comment]
@rrennick Yes, this is still applicable on WordPress 5.5.1 and WC Beta Tester 2.0.1 on 13" display.

**Comment by rrennick** [comment]
@slaFFik Thanks for  the quick reply. I've added a PR.
