### ISSUE TITLE
[GlobalStep - 4.2 Beta] Upon tapping "Activate WooCommerce" button, user should be redirected to install plugin page if WooCommerce plugin is not installed.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-beta-tester#62]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave-10.14.6-Safari(v13.0.5 )

**Steps to Reproduce:** 
1. Create a site using Ninja tool.
2. Tap on Plugins.
3. Tap on Add New.
4. Search Query Monitor, tap on "Install Now" and then on "Activate" button.
5. Search WooCommerce Beta Tester, tap on "Install Now" and then on "Activate" button.
6. Note that a popup is displayed  "WooCommerce Beta Tester requires WooCommerce to be installed and activated in order to serve updates"
7. Tap on "Activate WooCommerce" button.
8. Observe that "Plugin file does not exist." error message is displayed.

**Actual Result:**
Upon tapping "Activate WooCommerce" button, user should be redirected to install plugin page if WooCommerce plugin is not installed.

**Expected Result:**
Upon tapping  "Activate WooCommerce" button, website should redirect to install plugin page.

![#26514](https://user-images.githubusercontent.com/41110392/81952055-9b322d00-9623-11ea-86bd-137d06fcadcc.jpg)

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for reporting the issue. WooCommerce Beta tester is being developed in another repository: https://github.com/woocommerce/woocommerce-beta-tester/
​
I am going to move your bug report there

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Open"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
