### ISSUE TITLE
[GlobalStep - 4.3 Beta] Error message “Installation failed: Destination folder already exists.” is shown even if "WooCommerce" plugin is not installed

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-beta-tester#63]
## Description:
Error message “Installation failed: Destination folder already exists.” is shown even if "WooCommerce" plugin is not installed

## Environment:
**Windows 10**
- Browser: Chrome(Version 83.0.4103.61 (64-bit))
- Browser: Firefox(Version 77.0.1)(64-bit)

**MacBook Pro Version 10.15.5 (19F101)**
- Browser: Safari(Version 13.1.1)(15609.2.9.1.2)

## Steps to Reproduce:
1. Launch https://nursing-macaque.jurassic.ninja site.
1. Go to Add plugins.
1. Install and Activate Query Monitor and WooCommerec Beta tester.
1. Install WooCommerce Plugin.
1. Note that “Installation failed: Destination folder already exists.” Error message is displayed.
1. Now tap on Activate WooCommerce button.
1. Observe that "Plugin file does not exist" error message is dislayed.

## Actual Result:
“Installation failed: Destination folder already exists.” Error message is displayed even after plugin is not installed.

## Expected Result:
All the plugins should install properly.

## Artifact:
![#26814](https://user-images.githubusercontent.com/41110392/85047466-7f382300-b1af-11ea-95a6-d35e570f5e93.gif)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Note:** No logs generated.

**Comment by rrennick** [comment]
@gglobalstep Have you seen a recurrence of this issue?

**Comment by rrennick** [comment]
Closing for lack of feedback.
