### ISSUE TITLE
[GlobalStep – 4.3 RC1] [Windows 10] “WooCommerce” plugin gets deleted upon clicking multiple times on “Switch Version” button.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-beta-tester#64]
## Bug Description:
“WooCommerce” plugin gets deleted upon clicking multiple times on “Switch Version” button.

## Environment:
**Windows 10**
Browser: Chrome(Version 83.0.4103.61 (64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)

## Steps to Reproduce:
1. Create any site using Jurassic Ninja.
1. Add and activate required plugins.
1. To switch version go to WooCommerce Beta Tester.
1. Select 4.3 RC1. 
1. Click on Switch button.
1. On popup tap multiple time on "Switch Version" button.
1. Observe that WooCommerce” plugin gets delete.

## Actual Result:
“WooCommerce” plugin gets deleted upon clicking multiple times on “Switch Version” button.

## Expected Result:
“WooCommerce” plugin should not be deleted upon clicking multiple times on “Switch Version” button.

## Artifacts:

[#26873.zip](https://github.com/woocommerce/woocommerce/files/4832998/26873.zip)

**Comment by gglobalstep** [comment]
This issue is observed to be "**Fixed**" on WooCommerce 4.3 RC2.
**Environment:**
**Build:** WooCommerce 4.3 RC2
**Platform:**
MAC Mojave v10.14.6: Safari(v13.0.5)
Windows 10:
Chrome: v83.0.4103.116
Firefox: v77.0.1

**Comment by rrennick** [comment]
Closing as resolved.
