### ISSUE TITLE
function 'auto_update_woocommerce' not found

### ISSUE THREAD

**Issue by cristianozanca** [woocommerce/woocommerce-beta-tester#68]
Hi, this is the error on my WP/WC test install:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name in /var/www/wp.test/wp-includes/class-wp-hook.php on line 287

WC 4.4.0-rc.1 Installed Version
WP 5.5-RC2-48740
WC Beta Tester 2.0.1

The public function auto_update_woocommerce is on row n 345 of file class-wc-beta-tester.php inside the WooCommerce Beta Tester plugin

Hope it could help

**Comment by kkmuffme** [comment]
Could someone please fix this? This is super annoying as it's triggered a gazillion times on /wp-admin/plugins.php page

**Comment by rrennick** [comment]
This was also reported in #69 which provides more detail. Please follow this issue on #69.

**Comment by BackuPs** [comment]
is this gonna be fixed? still getting this error.

**Comment by rrennick** [comment]
> is this gonna be fixed?

It' been fixed but a new version of the plugin hasn't been released.
