### ISSUE TITLE
Invalid function call: auto_update_woocommerce

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-beta-tester#69]
I get the following warning:

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name
```

It appears the filter is added referencing a function instead of a public method of the class:

https://github.com/woocommerce/woocommerce-beta-tester/blob/47c03465c02d6dae2776fe0fb49992050281d4c5/includes/class-wc-beta-tester.php#L89

**Comment by kkmuffme** [comment]
Already has an issue: https://github.com/woocommerce/woocommerce-beta-tester/issues/68
