### ISSUE TITLE
Beta tester doesn't recognize beta or release candidate versions of WooCommerce.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-beta-tester#7]
Before you update WooCommerce to a beta or release candidate this warning doesn't appear, but once you are on a beta version the plugin doesn't seem to recognize WooCommerce anymore. It then prompts you to install WooCommerce. :)

![http://cld.wthms.co/bh2S](http://cld.wthms.co/bh2S+)

**Comment by ryanr14** [comment]
On that note as well the link is to WooThemes.com, can it rather direct you to the install plugin screen in the WordPress admin?

**Comment by Tobias-Conrad** [comment]
i can confirm this issue.
also woocommerce rc2 got deactivated on open the plugin page.

**Comment by KyleStilkey** [comment]
The reason for this issue is because this Plugin, when installing a new version it renames your plugin folder from WooCommerce to WooCommerce-WooCommerce(Version String Number) you can fix this buy going into your FTP and manually changing the folder's name back to WooCommerce.

**Comment by Tobias-Conrad** [comment]
please update your plugin to be happy with new folder your plugin creates.

​

**Comment by lukecav** [comment]
Still an issue when testing WC 3.1 RC1.
