### ISSUE TITLE
Maintainer missing in action

### ISSUE THREAD

**Issue by kkmuffme** [woocommerce/woocommerce-beta-tester#70]
WooCommerce Beta Tester hasn't had an update in almost a year and there are a few major issues, making this plugin hardly usable (as it generates loads of PHP notices).

Since some of the maintainers of the repo are official employees of automattic/woocommerce, could someone please ping anybody there or at least add me (or anyone) as a maintainer so these issues get fixed?

Especially with the new WC monthly release cycle this plugin is an essential for theme & plugin developers who want to keep their plugin's compatible at all times.

**Comment by rrennick** [comment]
Transferred this issue to the relevant repository.

**Comment by rrennick** [comment]
@kkmuffme Thanks for your offer of assistance. There is a PR for each of the outstanding issues: https://github.com/woocommerce/woocommerce-beta-tester/pulls?q=is%3Apr+is%3Aopen+label%3A%22status%3A+needs+review%22. It would be great if you had time to test these and provide us with feedback.

**Comment by kkmuffme** [comment]
Checked the 2 relevant PRs and left feedback
