### ISSUE TITLE
Version switching between tagged releases on .org

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-beta-tester#9]
Introduce a screen which lists tagged versions/releases from the .org repository. 

Releases will have a radio button beside. Checking a radio and clicking 'switch' button will cause that version to be downloaded and installed. Once successful, a confirmation will be shown.

Look to WP Rollback for inspiration - this has something similar.

**Comment by peterfabian** [comment]
Should this have a separate screen or live in the same settings screen as choosing which channel user wants to belong to?
Reply to myself: Put it under Tools menu, as suggested in the kick-off post for the plugin.
