### ISSUE TITLE
Console shows some error on the WooCommerce-->Setting page.  

### ISSUE THREAD

**Issue by apeksha10** [woocommerce/woocommerce-beta-tester#98]
Console shows some error on the WooCommerce-->Setting page.

Steps
1. WooCommerce activate version is 5.4.0-rc.1
2. Install and activate WooCommerce Beta Tester
3. Go to WooCommerce-->Setting page 

Error : GET https://first-localhost.local/wp-content/plugins/woocommerce-beta-tester/assets/css/admin.css?ver=5.7.2 net::ERR_ABORTED 404

Screenshot:  https://www.screencast.com/t/hQLENfTozCXl

**Comment by zhongruige** [comment]
Hi @apeksha10,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

* I installed the WooCommerce Beta Tester Plugin
* Navigated around the site, and saw the 404 on the GET request in the console

We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by apeksha10** [comment]
Hi @zhongruige,

Thank you so much for letting me know.

**Comment by rrennick** [comment]
The `assets/css` folder is in the generated zip so it looks like this was a mistake in the release process. I should be able to bump the version for a new release while testing the release script in a couple weeks.
